src/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('playlist_manager/', include('playlist_manager.urls'))
]

src/mysite/playlist_manager/urls.py
from django.urls import path
from . import views


app_name = 'playlist_manager'
urlpatterns = [
    path('', views.index, name='index'),
    path('playlist/<str:playlist_id>/', views.playlist, name='playlist')
]

src/mysite/playlist_manager/models.py
from django.db import models


class Playlist(models.Model):
    id = models.CharField(max_length=200, primary_key=True)
    title = models.CharField(max_length=200)
    # to get all videos, method is <Playlist>.video_set.all(), or video_set.create( VIDEO FIELDS )
    # this is also where you add methods

    def __str__(self):
        return self.title


class Video(models.Model):
    video_id = models.CharField(max_length=200, default='')
    title = models.CharField(max_length=200)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    index = models.IntegerField()

    def __str__(self):
        return str(self.index) + " " + str(self.title)

src/mysite/playlist_manager/forms.py
from django import forms


class PlaylistForm(forms.Form):
    pl_id = forms.CharField(label='Playlist ID:', max_length=100)

src/mysite/playlist_manager/views.py
from django.shortcuts import render, redirect
from .models import Playlist, Video
from django.urls import reverse
from .forms import PlaylistForm

import os
from dotenv import load_dotenv
import pyyoutube

load_dotenv()
API_KEY = str(os.getenv('API_KEY'))
api = pyyoutube.Api(api_key=API_KEY)


def index(request):
    if request.method == 'POST':
        form = PlaylistForm(request.POST)

        if form.is_valid():
            pl_id = form.cleaned_data['pl_id']

            return redirect('playlist_manager:playlist', playlist_id=pl_id)

    else:
        context = {'form': PlaylistForm()}
        return render(request, 'playlist_manager/index.html', context)


def playlist(request, playlist_id):
    # if playlist already exists in database
    try:
        pl = Playlist.objects.get(id=playlist_id)

    except Playlist.DoesNotExist:
        # TODO raise 404 if playlist isn't found
        pl_title = api.get_playlist_by_id(playlist_id=playlist_id).items[0].snippet.title
        pl = Playlist(id=playlist_id, title=pl_title)
        pl.save()

        # get videos
        pl_items = api.get_playlist_items(playlist_id=playlist_id, count=None, limit=50)

        for item in pl_items.items:
            pl.video_set.create(
                video_id=item.snippet.resourceId.videoId,
                title=item.snippet.title,
                index=item.snippet.position
            )

    context = {
        'playlist': pl,
        'video_list': list(pl.video_set.order_by('index'))
    }

    return render(request, 'playlist_manager/playlist.html', context)

src/mysite/playlist_manager/templates/playlist_manager/index.html
<!DOCTYPE html>
<html lang = "en">

<head>
    <title>Playlist Manager</title>
    <meta charset="UTF-8">
    <meta name="author" content="Alexander Lee">
    <meta name="description" content="">
</head>

<body>
    <h1>Playlist Manager</h1>

    <form action="{% url 'playlist_manager:index' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Go">
    </form>
</body>
</html>

src/mysite/playlist_manager/templates/playlist_manager/playlist.html
<!DOCTYPE html>
<html lang = "en">
{% load static %}
<head>
    <title>{{ playlist.title }}</title>
    <meta charset="UTF-8">
    <meta name="author" content="Alexander Lee">
    <link rel="stylesheet" href="{% static 'playlist_manager/styles/playlist.css' %}">
</head>
<body>
    <h1 class="head">{{ playlist.title }}</h1>

    <div class="flex-container">
        <div class="flex-child">
            <ol>
                {% for video in video_list %}
                    <li>{{ video.title }}</li>
                {% endfor %}
            </ol>
        </div>

        <div class="flex-child">
            <p>gaaaa</p>
        </div>
    </div>
</body>
</html>